Deps/update ott
theislab/moscot pull request #557
Opened 2023-06-21 16:14 UTC by MUCDK

2023-06-29 18:38 UTC, giovp commented
I think this can be closed for now?

2023-08-07 10:41 UTC, michalk8 requested changes
Looks good, just minor comments.

2023-08-07 10:41 UTC, michalk8 commented on src/moscot/backends/ott/solver.py
> +        epsilon: Optional[float] = 0.0,
This cannot be optional for LR solvers.

2023-08-07 10:41 UTC, michalk8 commented on tests/problems/space/test_mixins.py
> +    @pytest.mark.skip("TODO(giovp): regenerate solutions")
These should be regenerated now.

2023-08-07 12:31 UTC, merged