adding _celltype_mapping in AnalysisMixin
theislab/moscot pull request #585
Opened 2023-07-19 16:17 UTC by ArinaDanilina

#569

2023-07-20 12:04 UTC, MUCDK commented on src/moscot/base/problems/_mixins.py
> +    ):
missing return type

2023-07-20 12:04 UTC, MUCDK commented on src/moscot/base/problems/_mixins.py
> +
missing: 'raise NotImplementedError', otherwise the function won't do anything if none of the 'if' conditions are fulfilled.

2023-07-20 12:07 UTC, MUCDK commented
@giovp we would also wanna have this in the `TranslationProblem`. For the temporalProblem I don't know how much sense this makes. Users should not misinterpret, but maybe still consider putting this into the AnalysisMixin?

2023-07-20 12:09 UTC, MUCDK commented on src/moscot/base/problems/_mixins.py
> +    def _celltype_mapping(
why private?

Missing docstrings

2023-07-20 12:24 UTC, giovp commented
> @giovp we would also wanna have this in the `TranslationProblem`. For the temporalProblem I don't know how much sense this makes. Users should not misinterpret, but maybe still consider putting this into the AnalysisMixin?

I think analysis mixin makes sense but as private method and then expose it only in relevant bio problems

2023-07-20 14:04 UTC, MUCDK commented on src/moscot/problems/space/_mixins.py
> +    def celltype_mapping(
missing docstrings.
also introduce a variable "cell_transition_kwargs".

2023-07-20 14:05 UTC, MUCDK commented on src/moscot/problems/space/_mixins.py
> +    def celltype_mapping(
"cell_transition_kwargs" should be default types.MappingProxyType({}). Raise error if `cell_transition_kwargs` is not an empty `dict` although `cell_transition` is not used

2023-07-20 14:06 UTC, MUCDK commented
please link to the example with the function.

2023-10-10 15:37 UTC, giovp requested changes
this is looking really nice, could you add some tests and update notebooks @ArinaDanilina ?

2023-10-10 15:37 UTC, giovp commented on src/moscot/base/problems/_mixins.py
> +    def _cell_transition(
this probably should also change name ?

2023-10-11 08:38 UTC, MUCDK commented on src/moscot/base/problems/_mixins.py
> +    def _cell_transition(
this has been around for a while, no?

2023-12-12 08:40 UTC, giovp requested changes
missing write tests

2023-12-12 08:40 UTC, giovp commented on src/moscot/problems/time/_mixins.py
> +            other_adata=other_adata,
set to None

2023-12-12 08:40 UTC, giovp commented on src/moscot/problems/time/_mixins.py
> +        other_adata: Optional[str] = None,
remove

2023-12-12 08:40 UTC, giovp commented on src/moscot/problems/space/_mixins.py
> +                self.adata[idx].obs[key_added] = annotation
remove

2023-12-12 08:40 UTC, giovp commented on src/moscot/base/problems/_mixins.py
> +        # key_added: Optional[str] = None,
remove

2023-12-12 08:40 UTC, giovp commented on src/moscot/base/problems/_mixins.py
> +        # target_label: Optional[str] = "adata",
remove

2023-12-12 08:40 UTC, giovp commented on src/moscot/problems/cross_modality/_mixins.py
> +        source: K,
```suggestion
        source: K = "src",
```

2023-12-12 08:40 UTC, giovp commented on src/moscot/problems/space/_mixins.py
> +        other_adata: Optional[str] = None,
remove

2023-12-12 08:40 UTC, giovp commented on src/moscot/problems/space/_mixins.py
> +            other_adata=other_adata,
set to None or remove

2023-12-12 08:40 UTC, giovp commented on src/moscot/problems/space/_mixins.py
> +            self.adata_sc.obs[key_added] = annotation
remove

2023-12-12 08:40 UTC, giovp commented on src/moscot/problems/space/_mixins.py
> +            forward=not forward,  # inverted for MappingProblem
forward=forward
```suggestion
            forward=forward,
```

2023-12-12 08:40 UTC, giovp commented on src/moscot/problems/space/_mixins.py
> +        forward: bool,
default = False

2023-12-12 08:40 UTC, giovp commented on src/moscot/problems/space/_mixins.py
> +        annotation = self._annotation_mapping(
key=self.batch_key

2023-12-12 08:40 UTC, giovp commented on src/moscot/problems/space/_mixins.py
> +        # mp[("batch_0","tgt"), ("batch_1","tgt")] # from sc tgt to spatial batch
remove this comment

2023-12-12 08:40 UTC, giovp commented on src/moscot/problems/space/_mixins.py
> +        # target: str = "tgt",
this is a good default

2023-12-12 08:40 UTC, giovp commented on src/moscot/problems/space/_mixins.py
> +        source: str = "src",
this is not a good default, needs to be passed by user

2023-12-12 08:45 UTC, giovp commented
tests:
- create ground truth data 10x15 (src, tgt) for temporal problem and cross-modality problem.
- use `test_cell_transition` pipeline to get sense of how to construct the ground truth for testing.

2023-12-19 08:28 UTC, MUCDK commented on src/moscot/problems/space/_mixins.py
> +    ) -> pd.DataFrame:
Missing docstrings

2023-12-19 08:28 UTC, MUCDK commented on src/moscot/problems/space/_mixins.py
> +    def annotation_mapping(
missing docstrings

2023-12-19 08:28 UTC, MUCDK commented on src/moscot/problems/time/_mixins.py
> +    ) -> pd.DataFrame:
missing docstrings

2023-12-19 08:28 UTC, MUCDK commented on src/moscot/problems/time/_mixins.py
> +        return annotation
directly do `return self._annotation_mapping...`

2023-12-19 08:29 UTC, MUCDK commented on src/moscot/problems/space/_mixins.py
> +        return annotation
directly do `return self._ann...`

2023-12-19 08:29 UTC, MUCDK commented on src/moscot/problems/space/_mixins.py
> +        return annotation
unnecessary return. directly do `return self._anno...`

2023-12-19 08:29 UTC, MUCDK commented on src/moscot/problems/cross_modality/_mixins.py
> +        return annotation
unnecessaey return

2023-12-19 08:30 UTC, MUCDK requested changes
see comments

2023-12-19 08:51 UTC, MUCDK commented
Also, please add the link to the example.

2024-01-19 08:42 UTC, MUCDK commented on src/moscot/problems/cross_modality/_mixins.py
> +        This function transfers annotation labels (e.g. cell types) between groups of cells.
This function transfers annotations (e.g. cell type labels) between distributions of cells.

2024-01-19 08:44 UTC, MUCDK commented on src/moscot/problems/cross_modality/_mixins.py
> +            - ``'max'`` - pick the label of the annotated cell with the highest mapping weight.
...with the highest matching probability.

2024-01-19 08:46 UTC, MUCDK commented on src/moscot/problems/cross_modality/_mixins.py
> +        other_adata
I don't think the user specifies this. also see below, it is inferred. hence remove.

2024-01-19 08:46 UTC, MUCDK commented on src/moscot/problems/cross_modality/_mixins.py
> +        other_adata: Optional[str] = None,
remove, see comment below

2024-01-19 08:46 UTC, MUCDK commented on src/moscot/problems/cross_modality/_mixins.py
> +        scale_by_marginals: bool = True,
Don't expose this, you can still pass it in `kwargs`

2024-01-19 08:47 UTC, MUCDK commented on src/moscot/problems/space/_mixins.py
> +        scale_by_marginals: bool = True,
Remove

2024-01-19 08:47 UTC, MUCDK commented on src/moscot/problems/time/_mixins.py
> +        scale_by_marginals: bool = True,
remove

2024-01-19 08:48 UTC, MUCDK requested changes
regarding the comments in the docstring, please make sure that you change them everywhere (I only indicated in one of them)

2024-01-19 09:43 UTC, giovp approved these changes
really great work @ArinaDanilina !!!! final polish and then LGTM!

2024-01-19 09:43 UTC, giovp commented on src/moscot/problems/cross_modality/_mixins.py
> +              pick the label with the highest total matching probability.
```suggestion
              pick the label with the highest total matching probability.
              
```

2024-01-19 09:43 UTC, giovp commented on src/moscot/problems/cross_modality/_mixins.py
> +              pick the label with the highest total matching probability.
you might also have to indent further the bulletpoint, check readthedocs from this PR build how it looks like, if it looks wrong, then adapt by looking at how it's done in other places where bulletpoint are used in docstrings

2024-01-19 09:43 UTC, giovp commented on src/moscot/problems/cross_modality/_mixins.py
> +        :class:`~pandas.DataFrame`. - returns the DataFrame of transferred annotations.
```suggestion
        :class:`~pandas.DataFrame` - Returns the DataFrame of transferred annotations.
```

2024-01-19 09:43 UTC, giovp commented on src/moscot/problems/space/_mixins.py
> +        :class:`~pandas.DataFrame` - returns the DataFrame of transferred annotations.
```suggestion
        :class:`~pandas.DataFrame` - Returns the DataFrame of transferred annotations.
```

2024-01-19 09:43 UTC, giovp commented on src/moscot/problems/space/_mixins.py
> +        :class:`~pandas.DataFrame` - returns the DataFrame of transferred annotations.
```suggestion
        :class:`~pandas.DataFrame` - Returns the DataFrame of transferred annotations.
```

2024-01-19 09:43 UTC, giovp commented on src/moscot/problems/space/_mixins.py
> +              pick the label with the highest total matching probability.
here and in all other places where bulletpoints are used

2024-01-19 09:43 UTC, giovp commented on src/moscot/problems/time/_mixins.py
> +        :class:`~pandas.DataFrame` - returns the DataFrame of transferred annotations.
also here Returns

2024-01-19 10:53 UTC, MUCDK approved these changes
Thanks!

2024-01-19 11:04 UTC, merged