simulate cost matrices in simulate_data
theislab/moscot pull request #671
Opened 2024-03-14 10:38 UTC by ArinaDanilina

extensions from #636

2024-03-14 10:40 UTC, ArinaDanilina commented
also updates the notebooks

2024-03-14 11:29 UTC, MUCDK requested changes

2024-03-14 11:29 UTC, MUCDK commented on src/moscot/datasets.py
> +        If `None`, no linear cost matrix is generated.
Can we just generate them for all pairs of distributions?

2024-03-19 15:33 UTC, MUCDK approved these changes
Thanks Arina!

2024-03-20 08:00 UTC, merged