Add Sparse Geodesic Cost Support
theislab/moscot pull request #677
Opened 2024-03-20 14:57 UTC by selmanozleyen

Here are the steps I planned. I first want to ensure the tests work with this version and I am currently on that step.
- [ ] make sure it works on the new commit of ottjax (here: https://github.com/ott-jax/ott/commit/51a658aaa026528a3b9702e3d25c8f7af598cef0)
- [ ] don't densify sparse arrays for geodesic costs
- [ ] adjust and add tests 

ping: @MUCDK , @giovp

2024-04-09 07:39 UTC, giovp commented
- try increase the taus for the failing tests for FGW/GW problems
- default to None the n iterations

2024-04-09 12:23 UTC, selmanozleyen commented
I tried all of your suggestions and it only worked when I set the tau's to be 1.0 which is balanced. I checked again and it fails after this https://github.com/ott-jax/ott/commit/41906a2a1ade19aa154189fabd7c159a160c9bf3 commit specifically. I created a PR separately for the setting the defaults to None https://github.com/theislab/moscot/pull/686

2024-04-10 07:04 UTC, giovp commented
ok then i think we need to raise this to @michalk8 because it is not expected

2024-04-10 07:12 UTC, MUCDK commented
agree, can you maybe try to run the example without moscot, but directly with ott-jax @selmanozleyen ? This might help @michalk8

2024-04-17 09:41 UTC, selmanozleyen commented
> agree, can you maybe try to run the example without moscot, but directly with ott-jax @selmanozleyen ? This might help @michalk8

@MUCDK ok I created it here https://github.com/ott-jax/ott/issues/519

2024-05-09 13:01 UTC, MUCDK commented on src/moscot/backends/ott/_utils.py
> +    """If the input is sparse, convert it t dense.
"""If the input is sparse, convert it to dense.

2024-05-09 13:08 UTC, MUCDK requested changes
Can you please also update the tests with geodesic costs for other problems, e.g. https://github.com/theislab/moscot/blob/6cc22154caa96c30d2319b7268aa1e5d0c482dd2/tests/problems/time/test_temporal_problem.py#L252

Also, accordingly, please update https://github.com/theislab/moscot/blob/6cc22154caa96c30d2319b7268aa1e5d0c482dd2/src/moscot/utils/tagged_array.py#L106

2024-05-20 18:36 UTC, merged