Add user guide
theislab/moscot pull request #690
Opened 2024-04-30 06:49 UTC by ArinaDanilina

2024-05-06 06:20 UTC, MUCDK commented on docs/user_guide.md
> +In their original formulation, OT algorithms don't scale to large datasets du to their high computational complexity. Moscot overcomes this limitation by allowing for the use of low-rank solvers. in
somehow try to highlight the `solve` method, not having it in default font. also `-1`. Also link to the examples describing this.

2024-05-06 06:22 UTC, MUCDK commented on docs/user_guide.md
> +All moscot problems are in general aplciable to any modality, as the solution of the moscot problem only depends on pairwise distances of cells. Yet, it is up to the usre to apply the preprocessing.
applicable, typo.
same with users. 
working, too. 
"How to pass certain embeddings, please have a look at [example xyz]."

2024-05-06 06:22 UTC, MUCDK commented on docs/user_guide.md
> +moscot problems implement problem-specific downstream methods, so we recommend the user to use those. We also offer [generic solvers](#generic-problems) with a limited range of downstream application
... downstream methods, so we recommend to use task-specific moscot problems. Yet, we also offer...

2024-05-06 06:23 UTC, MUCDK requested changes
also add more stuff, please.

2024-05-07 07:26 UTC, giovp commented
missing:
- [ ] hyperparameters section 
- [ ] fill the table of the problems

2024-05-14 06:31 UTC, MUCDK commented on docs/user_guide.md
> +   * - :mod:`moscot.problems.cross_modality.TranslationProblem`
that's spatiotemporal

2024-05-14 06:31 UTC, MUCDK commented on docs/user_guide.md
> +   * - :mod:`moscot.problems.spatiotemporal.SpatioTemporalProblem`
that's Translationproblem

2024-05-14 06:31 UTC, MUCDK commented on docs/user_guide.md
> +In their original formulation, OT algorithms don't scale to large datasets du to their high computational complexity. Moscot overcomes this limitation by allowing for the use of low-rank solvers. in
Please also add a description for full rank `batch size` in linear OT

2024-05-14 06:34 UTC, MUCDK commented on docs/user_guide.md
> +moscot problems' `solve` methods have the following parameters that can be set depending on the specific task:
please reorder to 
1) epsilon, 2) tau, 3) alpha, 4) batch size, 5) rank

And then link to the examples, i.e. for more hyperaparameters please refer to ...

2024-05-14 06:34 UTC, MUCDK requested changes
minor changes

2024-05-14 07:24 UTC, MUCDK commented
Please also add a general reference to examples / tutorials at the end.

2024-05-29 06:37 UTC, MUCDK commented on docs/user_guide.md
> +Another option to use the full rank is to specify the `batch_size` parameter of the `solve` method. It determines the number of rows or columns of the cost matrix to materialize during the {term}`Sin
Can we have this before low-rank? and then say, for linear problems we can do the batch_size, which reduces memory complexity (but slightly increase time complexity).

and then we motivate the low-rank: Whenever time complexity in a linear problem (e.g. TemporalProblem) should be reduced, or memory/time complexity in a quadratic (enumarte / link quadratic problems here) problem should be reduced , we use low-rank OT.

2024-05-29 06:38 UTC, MUCDK commented on docs/user_guide.md
> +Moscot problems' `solve` methods have the following parameters that can be set depending on the specific task:
The `solve` method of moscot problems have a wide range of parameters. In the following, we discuss the most relevant ones:

2024-05-29 06:39 UTC, MUCDK commented on docs/user_guide.md
> +- $\varepsilon$ - {term}`Entropic regularization`.
[...] This determines the stochasticity of the map. The higher `epsilon`, the more stochastic the map is.

2024-05-29 06:42 UTC, MUCDK commented on docs/user_guide.md
> +- $\tau_a$ and $\tau_b$ - Parameters in $(0, 1]$ that define how {term}`unbalanced <unbalanced OT problem>` is the problem on the source and target {term}`marginals`. If $1$, the problem is {term}`ba
The lower tau, the more "unbalanced" the problem. Unbalancedness allows to automatically discard outliers, compensate for undesired distributional shifts, and model cell proliferation and apoptosis.

2024-05-29 06:43 UTC, MUCDK commented on docs/user_guide.md
> +- $\alpha$ - Parameter in $(0, 1]$ that interpolates between the {term}`quadratic term` and the {term}`linear term`. $\alpha = 1$ corresponds to the pure {term}`Gromov-Wasserstein` problem while $\al
... $\alpha$ (only in problems building upon `Fused Gromov-Wasserstein`).....

2024-05-29 06:43 UTC, MUCDK commented on docs/user_guide.md
> +- `batch_size` - Number of rows/columns of the cost matrix to materialize during the solver iterations. Larger value will require more memory.
....See above the scalability

2024-05-29 06:43 UTC, MUCDK commented on docs/user_guide.md
> +For more hyperparameters and their usage please refer to {doc}`/notebooks/examples/solvers/200_linear_problems_advanced` and {doc}`/notebooks/examples/solvers/400_quad_problems_advanced`.
you should also link to basic `solve` examples.

2024-05-29 06:44 UTC, MUCDK requested changes
THanks

2024-06-11 05:46 UTC, MUCDK commented on docs/user_guide.md
> +All moscot problems are in general applicable to any modality, as the solution of the moscot problem only depends on pairwise distances of cells. Yet, it is up to the users to apply the preprocessing
do we really want to link to the translation tutorial? I thought about https://github.com/theislab/moscot/issues/643

2024-06-11 05:47 UTC, MUCDK requested changes
other than this one link it looks fine. If the notebook hasn't been written / not close to being finished, we can also merge first, then please open an issue to replace the link in future times.

2024-06-22 10:17 UTC, MUCDK commented on docs/user_guide.md
> +For tutorials showcasing use cases for data analysis please see {doc}`/notebooks/tutorials/index`.\
showcasing use cases.... not good. replace e.g. by "demonstrating"

2024-06-22 10:19 UTC, MUCDK commented on docs/user_guide.md
> +Moscot builds upon three principles:
not twice "builds upon". 
e.g. Moscot follows three design principles

2024-06-22 10:21 UTC, MUCDK requested changes
thanks

2024-06-25 07:09 UTC, MUCDK approved these changes
thanks

2024-06-25 07:09 UTC, merged